### ISSUE TITLE
Crash when connecting on mobile

### ISSUE THREAD

**Issue by TextualMold9830** [jaydevelopsstuff/PlutoRewrite#3]
When I'm connection on mobile after CompleteConnectionAndSpawn is sent Terraria crashes.

**Comment by jaydevelopsstuff** [comment]
This server was never intended for mobile, I'm not sure that the protocol is even the same.

**Comment by TextualMold9830** [comment]
The protocol on mobile is version 274. I also saw that on PC an error is thrown and the client doesn't connect.

**Comment by jaydevelopsstuff** [comment]
> The protocol on mobile is version 274. I also saw that on PC an error is thrown and the client doesn't connect.

Yeah, I haven't updated Pluto for the latest protocol in a while so that doesn't surprise me. If you'd like you can fork, open a pr and try to fix it for yourself and I'll merge it but I don't have the time to work on this project anymore.

**Comment by TextualMold9830** [comment]
I don't know how to update it. Any instructions?

**Comment by TextualMold9830** [comment]
PC seems to also crash:

Read:ManaEffect [43]
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TextualMold9830** [comment]
On a new character, on PC the player can connect but the world is empty
